/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { StageConfig } from '../types/game';

export const DEFAULT_STAGE_CONFIG: StageConfig = {
  "gridRadius": 4,
  "hexRadius": 37,
  "hexGap": 0,
  "stageX": 300,
  "stageY": 545,
  "rotation": 0,
  "stageBgColor": "transparent",
  "backgroundFrost": true,
  "backgroundFrostBlur": 0,
  "backgroundFrostOpacity": 9,
  "backgroundFrostTint": "#bdffe9",
  "strokeWidth": 1,
  "strokeColor": "#192e1e",
  "strokeOpacity": 47,
  "cornerRadius": 0,
  "fillColor": "#d0f5f1",
  "fillOpacity": 47,
  "showCoordinates": false,
  "interactiveHover": true,
  "windowWidth": 603,
  "windowHeight": 1311,
  "windowRadius": 100,
  "windowBg": "#ffffff",
  "outerBg": "#28282a",
  "windowShadowBlur": 10,
  "windowShadowOpacity": 50,
  "notchWidth": 140,
  "notchHeight": 55,
  "notchTop": 22,
  "notchRadius": 50,
  "notchColor": "#000000",
  "notchVisible": true,
  "zoomMode": "fit",
  "customZoom": 75,
  "backgroundImage": "background01.jpeg",
  "gems": {
    "size": 44,
    "theme": "gem",
    "glowIntensity": 0,
    "showLabel": false,
    "showFacets": true,
    "shapes": {
      "bloom": "diamond",
      "stella": "diamond",
      "flora": "circle",
      "musa": "diamond",
      "tecna": "square",
      "aisha": "droplet"
    },
    "sizes": {
      "bloom": 44,
      "stella": 44,
      "flora": 44,
      "musa": 44,
      "tecna": 57,
      "aisha": 44
    },
    "colors": {
      "bloom": "#3E63FF",
      "stella": "#FFB238",
      "flora": "#FF9AC5",
      "musa": "#FF4F5E",
      "tecna": "#9B59FF",
      "aisha": "#2FD9C4"
    },
    "customImages": {
      "bloom": "gems/bloom.png",
      "stella": "gems/stella.png",
      "flora": "gems/flora.png",
      "musa": "gems/musa.png",
      "tecna": "gems/tecna.png",
      "aisha": "gems/aisha.png"
    }
  },
  "animation": {
    "duration": 350,
    "easing": "bounce",
    "dragScale": 1.35,
    "snapDistance": 70,
    "enforceAdjacency": true,
    "enableSparkles": true,
    "swapPulseGlow": true,
    "autoSwapOnDrag": true,
    "enableChainPop": true,
    "minMatchCount": 3,
    "popChainDelay": 110,
    "refillAfterPop": true,
    "spawnDelay": 320,
    "spawnDuration": 420,
    "enablePopSound": true,
    "enableSwapSound": true,
    "tapScale": 1.3,
    "tapLiftOffsetY": -10,
    "tapLiftTransition": 180,
    "enableTapSelect": true
  },
  "energy": {
    "enabled": true,
    "maxEnergy": 215,
    "energyPerSwap": 15,
    "dragDrainRate": 10,
    "refillRate": 25,
    "refillDelay": 450,
    "barWidth": 470,
    "barHeight": 18,
    "barTop": 106,
    "barRadius": 9999,
    "primaryColor": "#FF4F5E",
    "secondaryColor": "#FF9AC5",
    "backgroundColor": "rgba(20, 20, 30, 0.65)",
    "borderColor": "#F5B7D9",
    "borderWidth": 0.5,
    "showLabel": true,
    "glowEffect": true,
    "shakeOnDepleted": true
  },
  "timer": {
    "enabled": true,
    "duration": 60,
    "barWidth": 470,
    "barHeight": 18,
    "barTop": 134,
    "barRadius": 9999,
    "primaryColor": "#2FD9C4",
    "secondaryColor": "#3E63FF",
    "backgroundColor": "rgba(20, 20, 30, 0.65)",
    "borderColor": "#2FD9C4",
    "borderWidth": 0.5,
    "glowEffect": true,
    "showTimeText": true
  },
  "enemyGem": {
    "enabled": true,
    "name": "Shadow Core",
    "color": "#3b0764",
    "accentColor": "#0a0014",
    "glowColor": "#581c87",
    "smokeIntensity": 15,
    "smokeColor": "#2e0249",
    "centerHexId": -1,
    "pulseSpeed": 2.5,
    "enablePulsate": true,
    "pulseScale": 1.06,
    "smallEnemyRotate": true,
    "smallEnemyRotateSpeed": 16,
    "smallEnemyRotateDirection": "clockwise",
    "baseScale": 1.15,
    "maxHits": 25,
    "damagePerMatch": 1,
    "damageCalculation": "perAdjacentGem",
    "healthBarWidth": 140,
    "healthBarHeight": 16,
    "healthBarOffsetY": 5,
    "showHealthText": true,
    "healthBarColor": "#c084fc",
    "shakeIntensity": 12,
    "shakeDuration": 400,
    "defeatDelay": 1500,
    "showHealthBar": true,
    "immovableCount": 4,
    "smallEnemySize": 44,
    "smallEnemyRotation": 30,
    "bigEnemyRotation": 90,
    "imageUrl": "enemy/shadow_core.png",
    "companionImageUrl": "enemy/companion.png",
    "enemyHexBgStart": "#250238",
    "enemyHexBgMid": "#3b0764",
    "enemyHexBgEnd": "#18002a",
    "enemyHexStroke": "#581c87",
    "enemyHexOpacity": 92,
    "enemyHexStrokeOpacity": 100
  },
  "powerups": {
    "enabled": true,
    "defaultCharges": 3,
    "overdriveDuration": 8,
    "bottomOffset": 155,
    "dockWidth": 540,
    "cardHeight": 210,
    "cardGap": 14,
    "cardRadius": 24,
    "iconSize": 80,
    "glowIntensity": 100
  },
  "currencies": {
    "softCurrencyIcon": "currencies/coin.png",
    "hardCurrencyIcon": "currencies/crystal.png",
    "softCurrencyName": "Pixie Coins",
    "hardCurrencyName": "Magic Crystals",
    "startingSoftCurrency": 2450,
    "startingHardCurrency": 150,
    "softCurrencyLeft": 46,
    "hardCurrencyRight": 46,
    "topBarYOffset": 0,
    "pauseGap": 8
  }
};
